In [ ]:
# Two ways to create Array:
# 1. Python Array Module
# 2. Python NumPy Module (Recommended)

In [ ]:
# 1. Python Array Module:
#    - Python provides an "array" module to create arrays that store elements of the 
#      same data type.
#    - Unlike a normal Python list, an array stores values of a specific data type.
#    - Syntax: 
#      - array.array('typecode', [elements])
#      - array.array('i', [10, 20, 30])
#        - 'i' → typecode
#        - [10, 20, 30] → elements stored in the array
#
#    - Typecodes: A typecode tells Python what type of data the array will store.
#      ------------------------------------------------
#      Typecode    Data Type              Typical Size
#      ------------------------------------------------
#      'i'         Signed Integer         2 or 4 bytes
#      'I'         Unsigned Integer       2 or 4 bytes
#      'u'         Unicode Character     2 or 4 bytes
#      'h'         Signed Short Integer  2 bytes
#      'H'         Unsigned Short        2 bytes
#      'l'         Signed Long Integer   4 or 8 bytes
#      'L'         Unsigned Long         4 or 8 bytes
#      'f'         Float                 4 bytes
#      'd'         Double                8 bytes
#
# Note: The exact size of some typecodes can depend on the platform and Python 
#       implementation.

In [ ]:
# 1. Create and Print integer array:

from array import *

val = array('i', [1, 2, 3, 4, 5, 6])

# Print using range():
for i in range(len(val)):
    print(val[i], end=" ")
    
# Print using enhanced for-loop:
print('\n')
for x in val:
    print(x, end=", ")

1 2 3 4 5 6 

1, 2, 3, 4, 5, 6, 

In [ ]:
# 2. Create a decimal array using the 'd' typecode.

from array import *

val = array('d', [1, 2, 3, 4, 5, 6, 7.5])

# Print using range():
for i in range(len(val)):
    print(val[i], end=" ")
    
# Print using enhanced for-loop:
print('\n')
for x in val:
    print(x, end=", ")

1.0 2.0 3.0 4.0 5.0 6.0 7.5 

1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.5, 

typecode is: d


In [ ]:
# 3. Print array typecode

from array import *

val = array('d', [1, 2, 3, 4, 5, 6, 7.5])
print('typecode is:', val.typecode)

typecode is: d


In [ ]:
# 4. Reverse an array:

from array import *

val = array('i', [1, 2, 3, 4, 5, 6])

val.reverse()
for i in range(len(val)):
    print(val[i], end=" ")

6 5 4 3 2 1 

In [27]:
# 5. Insert element in an array:

from array import *

val = array('i', [1, 2, 3, 4, 5, 6])

# Insert at 2nd element: val.insert(index, element)
val.insert(1, 50)

# Insert element at the end: val.append(element)
val.append(100)

for i in range(len(val)):
    print(val[i], end=" ")

1 50 2 3 4 5 6 100 

In [28]:
# 6. Replace Element in an array:

from array import *

val = array('i', [1, 2, 3, 4, 5, 6])

# Replace element
val[2] = 200

for i in range(len(val)):
    print(val[i], end=" ")

1 2 200 4 5 6 

In [30]:
# 7. Copy Array Elements to a New Array

from array import *

val = array('i', [1, 2, 3, 4, 5, 6])

# Copy Array Elements 
# a. val.typecode       : Gets the typecode of the existing array.
# b. x for x in val     : Loop chala k old value to new value m store kr denge
# c. array(va.typecode) : Creates a new array using the same typecode.
copyArr = array(val.typecode, (x*3 for x in val))

for i in range(len(copyArr)):
    print(copyArr[i], end=" ")

3 6 9 12 15 18 

In [ ]:
# 8. Delete an Array Element: 
#    - pop() tab use krte hai jab humein pta hai kis index se element remove krna hai.
#    - remove() tab use krte hai jab humein index nhi pta aur sirf element pta hai

from array import *

val = array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

# Delete element at index-3
val.pop(3)

# Delete element at last index
val.pop()

# Remove element-10
val.remove(10)

for i in range(len(val)):
    print(val[i], end=" ")

1 2 3 5 6 7 8 9 11 12 13 14 

In [ ]:
# 9. Slice part of Array:

from array import *

val = array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slice = val[startingIndex:EndingIndex]
slicedArrOne = val[2 : 5]
for i in range(len(slicedArrOne)):
    print(slicedArrOne[i], end=" ")
    
print('\n')

# Slice = val[startingIndex:lastThreeElementNhiChahiye]
slicedArrTwo = val[2 : -3]
for i in range(len(slicedArrTwo)):
    print(slicedArrTwo[i], end=" ")
    
print('\n')
    
# ReverseArray = val[::stepmove] 
# - 1 : 1-step move
# - 2 : 2-step move
# - -1: reverse step move
reverseArr = val[::-1]
for i in range(len(reverseArr)):
    print(reverseArr[i], end=" ")


3 4 5 

3 4 5 6 7 

1 4 7 10 

In [ ]:
# 10. Dynamic Array using User Input

from array import *

# Create an Empty Array
arr = array('i', [])

# Take the Number of Elements from the User
n = int(input('Enter a number:'))

# Add Elements to the Array
for i in range(0, n):
    arr.append(int(input('Enter next input:')))
    
# Print the Array Elements
for x in arr:
    print(x, end=" ")

5 4 3 2 1 

In [44]:
# 11. Find Index of an Element

from array import *

arr = array('i', [12, 23, 45, 234, 134, 235])

# Find idx of an element
idx = arr.index(45)
    
# Print the index
print('idx:', i)

idx: 4


In [45]:
# Install NumPy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
from numpy import *

# Homogenous Array
val = array([1, 2, 4])

for i in range(len(val)):
    print(val[i], end=" ")
    
print('\n')

for x in val:
    print(x, end=" ")

1.0 2.0 4.5 

1.0 2.0 4.5 

In [ ]:
from numpy import *

# Heterogenous Array
val = array([1, 2, 4.5, 'a'])

for x in val:
    print(x, end=" ")

1 2 4.5 a 

1 2 4.5 a 

In [56]:
from numpy import *

# Typecasting to float
val = array([1, 2, 4], float)

for x in val:
    print(x, end=" ")

1.0 2.0 4.0 

In [ ]:
# Create an Array Using NumPy's linspace()

from numpy import *

# Create an array of 5 equally spaced values starting from 10 and ending at 20.
# - linspace(start, stop, number_of_values)
#   - 10 -> starting value
#   - 20 -> Ending value
#   - 5  -> Total number of values
# - The values will be: 10, 12.5, 15, 17.5, 20

val = linspace(10, 20,5)

for x in val:
    print(x, end=" ")

10.0 12.5 15.0 17.5 20.0 

In [59]:
# Create an Array using NumPy's arange:

from numpy import *

# Create an array of numbers starting from 10 and going up to, but not including, 20.
# - arange(start, stop, step)
#   10 -> Starting Value
#   20 -> Ending Limit (20 is NOT included)
#   2  -> Difference between consecutive values
# - The values will be: 10, 12, 14, 16, 18
val = arange(10, 20, 2)

for x in val:
    print(x, end=" ")

10 12 14 16 18 

In [ ]:
# Create an Array of Zeros Using NumPy's zeros()
from numpy import *

# Create a NumPy array containing 10 zeros.
# - zeros(number_of_elements)
# - 10: Number of elements in the array
val = zeros(10)

for x in val:
    print(x, end=" ")

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 

In [ ]:
# Create an Array of Zeros Using NumPy's ones()
from numpy import *

# Create a NumPy array containing 10 ones.
# - ones(number_of_elements)
# - 10: Number of elements in the array
val = ones(10)

for x in val:
    print(x, end=" ")

1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 

In [ ]:
# Create an Array of Zeros Using NumPy's full()
from numpy import *

# Create a NumPy array containing 10 elements, where every element has the value 5.
# - full(number_of_elements, value)
# - 10: Number of elements in the array
# - 5 : Value stored in every element
val = full(10, 5)

for x in val:
    print(x, end=" ")

In [ ]:
# Create a Multi-Dimensional Array Using NumPy

from numpy import *

# a. Zero-Dimensional Array (One-Element)
zero = array(10)
print(zero)

# b. One-Dimensional Array
one = array([1, 2, 3, 4, 5])
print(one)

# c. Two-Dimensional Array: Collection of One-Dimensional Array
two = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two)

# d. Three-Dimensional Array: 
#    - Collection of Two-Dimensional Array
#    - Dimension should be equal
three = array([
    [ [1, 2], [3, 4] ],
    [ [5, 6], [7, 8] ]
])
print(three)

10
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
